### PR TITLE
Add Bedwars and Skywars Teams AutoPlay

### PR DESCRIPTION
**Pull request by SleepingPig35**
Add Bedwars and Skywars Teams AutoPlay - have not tested, I cannot build Raven-bS normally even before this commit - I hate Java. Can someone please send me the compiled jar for testing! Thank you.

### CODE REVIEW

**Comment by TejasLamba2006** [comment]
Hello @SleepingPig35,

I will be happy to assist you with this pull request.

Would you prefer me to simply provide the jar file after building, or guide you through the process of creating one?

**Comment by SleepingPig35** [comment]
The jar file please

**Comment by TejasLamba2006** [comment]
Hello @SleepingPig35,

I got an error while building
```js
> Configure project :
This mapping 'stable_20' was designed for MC 1.8.8! Use at your own peril.
WARNING: You are using an unsupported version of ForgeGradle.
Please consider upgrading to ForgeGradle 5 and helping in the efforts to get old versions working on the modern toolchain.
See https://gist.github.com/TheCurle/fe7ad3ede188cbdd15c235cc75d52d4a for more info on contributing.
Version string 'unspecified' does not match SemVer specification
You should try SemVer : http://semver.org/

> Task :compileJava
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
Note: Loading searge mappings from C:\Users\welcome\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_stable\20\srgs\mcp-srg.srg
Note: Loading notch mappings from C:\Users\welcome\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_stable\20\srgs\mcp-notch.srg
Note: Writing refmap to D:\old-drive\Source-Codes\Minecraft STUFF\temp\build\tmp\compileJava\compileJava-refmap.json
Note: Writing refmap to D:\old-drive\Source-Codes\Minecraft STUFF\temp\build\tmp\compileJava\compileJava-refmap.json
Note: Writing searge output SRGs to D:\old-drive\Source-Codes\Minecraft STUFF\temp\build\tmp\compileJava\mcp-srg.srg
Note: Writing notch output SRGs to D:\old-drive\Source-Codes\Minecraft STUFF\temp\build\tmp\compileJava\mcp-notch.srg
D:\old-drive\Source-Codes\Minecraft STUFF\temp\build\sources\main\java\keystrokesmod\module\impl\other\AutoPlay.java:66: error: duplicate case label
                                                case 5:
                                                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 22s
7 actionable tasks: 7 executed
```

**Comment by SleepingPig35** [comment]
hmm okay

**Comment by SleepingPig35** [comment]
Try again

**Comment by SleepingPig35** [comment]
@TejasLamba2006 I'm stupid xD I copied it wrong but it should work now

**Comment by TejasLamba2006** [comment]
Hello @SleepingPig35,

I sent the file on Discord in DMs as Github doens't support uploading of `jar` files.

image

**Comment by SleepingPig35** [comment]
Okay thank you, I will test now.

**Comment by SleepingPig35** [comment]
Confirmed: working.

**Comment by xia-mc** [comment]
Thank you!

**Comment by xia-mc** [comment]
@SleepingPig35 BTW, are you in Discord? I would like to know your name thx

**Comment by SleepingPig35** [comment]
@xia-mc itzapig

**Pull request merged**
