### PR TITLE
Add NoGround Mode in Criticals

### PR DESCRIPTION
**Pull request by KgDW**

### CODE REVIEW

**Comment by xia-mc** [comment]
bypass?

**Review by TejasLamba2006 — APPROVED** [review]
The implementation of the "NoGround" mode in the `Criticals` module is well-executed and adds valuable functionality. The code is clean, and the new setting integrates seamlessly. I approve the pull request as it stands, with the suggestion to ensure all necessary imports and dependencies are correctly handled. No further changes are required.

**Comment by TejasLamba2006** [comment]
> bypass?

wdym?

**Comment by xia-mc** [comment]
Thanks!

**Pull request merged**
